from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime

class RecordingCreate(BaseModel):
    recordingId: str = Field(..., description="Unique identifier for the recording session generated by device")
    deviceId: Optional[str] = Field(None, description="Device identifier that recorded the video")
    startTime: Optional[datetime] = None
    endTime: Optional[datetime] = None
    durationSeconds: Optional[int] = None
    fileSizeBytes: Optional[int] = None
    filePath: Optional[str] = None
    status: Optional[str] = "uploading"

class RecordingUpdate(BaseModel):
    startTime: Optional[datetime] = None
    endTime: Optional[datetime] = None
    durationSeconds: Optional[int] = None
    fileSizeBytes: Optional[int] = None
    filePath: Optional[str] = None
    status: Optional[str] = None

class RecordingResponse(BaseModel):
    id: str
    recordingId: str
    deviceId: Optional[str] = None
    busId: Optional[str] = None
    routeId: Optional[str] = None
    startTime: Optional[datetime] = None
    endTime: Optional[datetime] = None
    durationSeconds: Optional[int] = None
    fileSizeBytes: Optional[int] = None
    filePath: Optional[str] = None
    status: str
    createdAt: Optional[datetime] = None
    updatedAt: Optional[datetime] = None

    class Config:
        from_attributes = True
